package cn.edu.gdut.llc.mybatis.model;

import java.util.Date;

public class File {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_id
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Integer fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_category
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String fileCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_title
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String fileTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_url
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String fileUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_note
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String fileNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_visit
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Integer fileVisit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_update_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Date fileUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_md5
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String fileMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_location
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String fileLocation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_id
     *
     * @return the value of file.file_id
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Integer getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_id
     *
     * @param fileId the value for file.file_id
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setFileId(Integer fileId) {
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_category
     *
     * @return the value of file.file_category
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getFileCategory() {
        return fileCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_category
     *
     * @param fileCategory the value for file.file_category
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setFileCategory(String fileCategory) {
        this.fileCategory = fileCategory == null ? null : fileCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_title
     *
     * @return the value of file.file_title
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getFileTitle() {
        return fileTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_title
     *
     * @param fileTitle the value for file.file_title
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setFileTitle(String fileTitle) {
        this.fileTitle = fileTitle == null ? null : fileTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_url
     *
     * @return the value of file.file_url
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_url
     *
     * @param fileUrl the value for file.file_url
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_note
     *
     * @return the value of file.file_note
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getFileNote() {
        return fileNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_note
     *
     * @param fileNote the value for file.file_note
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setFileNote(String fileNote) {
        this.fileNote = fileNote == null ? null : fileNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_visit
     *
     * @return the value of file.file_visit
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Integer getFileVisit() {
        return fileVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_visit
     *
     * @param fileVisit the value for file.file_visit
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setFileVisit(Integer fileVisit) {
        this.fileVisit = fileVisit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_update_time
     *
     * @return the value of file.file_update_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Date getFileUpdateTime() {
        return fileUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_update_time
     *
     * @param fileUpdateTime the value for file.file_update_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setFileUpdateTime(Date fileUpdateTime) {
        this.fileUpdateTime = fileUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_md5
     *
     * @return the value of file.file_md5
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getFileMd5() {
        return fileMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_md5
     *
     * @param fileMd5 the value for file.file_md5
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5 == null ? null : fileMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_location
     *
     * @return the value of file.file_location
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getFileLocation() {
        return fileLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_location
     *
     * @param fileLocation the value for file.file_location
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setFileLocation(String fileLocation) {
        this.fileLocation = fileLocation == null ? null : fileLocation.trim();
    }
}