package cn.edu.gdut.llc.mybatis.model;

import java.util.Date;

public class Guides {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guides.id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guides.type
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guides.title
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guides.cover_pic
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer coverPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guides.url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guides.keyword
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guides.note
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guides.origin
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guides.release_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guides.update_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guides.file
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guides.visit
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer visit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column guides.content
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guides.id
     *
     * @return the value of guides.id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guides.id
     *
     * @param id the value for guides.id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guides.type
     *
     * @return the value of guides.type
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guides.type
     *
     * @param type the value for guides.type
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guides.title
     *
     * @return the value of guides.title
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guides.title
     *
     * @param title the value for guides.title
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guides.cover_pic
     *
     * @return the value of guides.cover_pic
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getCoverPic() {
        return coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guides.cover_pic
     *
     * @param coverPic the value for guides.cover_pic
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setCoverPic(Integer coverPic) {
        this.coverPic = coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guides.url
     *
     * @return the value of guides.url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guides.url
     *
     * @param url the value for guides.url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guides.keyword
     *
     * @return the value of guides.keyword
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guides.keyword
     *
     * @param keyword the value for guides.keyword
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guides.note
     *
     * @return the value of guides.note
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guides.note
     *
     * @param note the value for guides.note
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guides.origin
     *
     * @return the value of guides.origin
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guides.origin
     *
     * @param origin the value for guides.origin
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guides.release_time
     *
     * @return the value of guides.release_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guides.release_time
     *
     * @param releaseTime the value for guides.release_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guides.update_time
     *
     * @return the value of guides.update_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guides.update_time
     *
     * @param updateTime the value for guides.update_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guides.file
     *
     * @return the value of guides.file
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guides.file
     *
     * @param file the value for guides.file
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setFile(Integer file) {
        this.file = file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guides.visit
     *
     * @return the value of guides.visit
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getVisit() {
        return visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guides.visit
     *
     * @param visit the value for guides.visit
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setVisit(Integer visit) {
        this.visit = visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column guides.content
     *
     * @return the value of guides.content
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column guides.content
     *
     * @param content the value for guides.content
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}