package cn.edu.gdut.llc.mybatis.model;

public class InfoFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_file.info_file_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer infoFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_file.infoId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer infoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column info_file.fileId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer fileid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_file.info_file_id
     *
     * @return the value of info_file.info_file_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getInfoFileId() {
        return infoFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_file.info_file_id
     *
     * @param infoFileId the value for info_file.info_file_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setInfoFileId(Integer infoFileId) {
        this.infoFileId = infoFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_file.infoId
     *
     * @return the value of info_file.infoId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_file.infoId
     *
     * @param infoid the value for info_file.infoId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setInfoid(Integer infoid) {
        this.infoid = infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column info_file.fileId
     *
     * @return the value of info_file.fileId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column info_file.fileId
     *
     * @param fileid the value for info_file.fileId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }
}