package cn.edu.gdut.llc.mybatis.model;

public class Infopic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infopic.id
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infopic.infoId
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    private Integer infoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infopic.picId
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    private Integer picid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopic.id
     *
     * @return the value of infopic.id
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopic.id
     *
     * @param id the value for infopic.id
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopic.infoId
     *
     * @return the value of infopic.infoId
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    public Integer getInfoid() {
        return infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopic.infoId
     *
     * @param infoid the value for infopic.infoId
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    public void setInfoid(Integer infoid) {
        this.infoid = infoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infopic.picId
     *
     * @return the value of infopic.picId
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    public Integer getPicid() {
        return picid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infopic.picId
     *
     * @param picid the value for infopic.picId
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    public void setPicid(Integer picid) {
        this.picid = picid;
    }
}