package cn.edu.gdut.llc.mybatis.model;

public class LoggerInfosWithBLOBs extends LoggerInfos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logger_infos.param_data
     *
     * @mbggenerated Sun Jan 14 20:24:45 CST 2018
     */
    private String paramData;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column logger_infos.return_data
     *
     * @mbggenerated Sun Jan 14 20:24:45 CST 2018
     */
    private String returnData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logger_infos.param_data
     *
     * @return the value of logger_infos.param_data
     *
     * @mbggenerated Sun Jan 14 20:24:45 CST 2018
     */
    public String getParamData() {
        return paramData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logger_infos.param_data
     *
     * @param paramData the value for logger_infos.param_data
     *
     * @mbggenerated Sun Jan 14 20:24:45 CST 2018
     */
    public void setParamData(String paramData) {
        this.paramData = paramData == null ? null : paramData.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column logger_infos.return_data
     *
     * @return the value of logger_infos.return_data
     *
     * @mbggenerated Sun Jan 14 20:24:45 CST 2018
     */
    public String getReturnData() {
        return returnData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column logger_infos.return_data
     *
     * @param returnData the value for logger_infos.return_data
     *
     * @mbggenerated Sun Jan 14 20:24:45 CST 2018
     */
    public void setReturnData(String returnData) {
        this.returnData = returnData == null ? null : returnData.trim();
    }
}