package cn.edu.gdut.llc.mybatis.model;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.path
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.component
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String component;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.name
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.iconCls
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String iconcls;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.keepAlive
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Boolean keepalive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.requireAuth
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Boolean requireauth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.parentId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.enabled
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Boolean enabled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.id
     *
     * @return the value of menu.id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.id
     *
     * @param id the value for menu.id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.url
     *
     * @return the value of menu.url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.url
     *
     * @param url the value for menu.url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.path
     *
     * @return the value of menu.path
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.path
     *
     * @param path the value for menu.path
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.component
     *
     * @return the value of menu.component
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getComponent() {
        return component;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.component
     *
     * @param component the value for menu.component
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setComponent(String component) {
        this.component = component == null ? null : component.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.name
     *
     * @return the value of menu.name
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.name
     *
     * @param name the value for menu.name
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.iconCls
     *
     * @return the value of menu.iconCls
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getIconcls() {
        return iconcls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.iconCls
     *
     * @param iconcls the value for menu.iconCls
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setIconcls(String iconcls) {
        this.iconcls = iconcls == null ? null : iconcls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.keepAlive
     *
     * @return the value of menu.keepAlive
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Boolean getKeepalive() {
        return keepalive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.keepAlive
     *
     * @param keepalive the value for menu.keepAlive
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setKeepalive(Boolean keepalive) {
        this.keepalive = keepalive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.requireAuth
     *
     * @return the value of menu.requireAuth
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Boolean getRequireauth() {
        return requireauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.requireAuth
     *
     * @param requireauth the value for menu.requireAuth
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setRequireauth(Boolean requireauth) {
        this.requireauth = requireauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.parentId
     *
     * @return the value of menu.parentId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.parentId
     *
     * @param parentid the value for menu.parentId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.enabled
     *
     * @return the value of menu.enabled
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.enabled
     *
     * @param enabled the value for menu.enabled
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }
}