package cn.edu.gdut.llc.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PicturesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public PicturesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPicIdIsNull() {
            addCriterion("pic_id is null");
            return (Criteria) this;
        }

        public Criteria andPicIdIsNotNull() {
            addCriterion("pic_id is not null");
            return (Criteria) this;
        }

        public Criteria andPicIdEqualTo(Integer value) {
            addCriterion("pic_id =", value, "picId");
            return (Criteria) this;
        }

        public Criteria andPicIdNotEqualTo(Integer value) {
            addCriterion("pic_id <>", value, "picId");
            return (Criteria) this;
        }

        public Criteria andPicIdGreaterThan(Integer value) {
            addCriterion("pic_id >", value, "picId");
            return (Criteria) this;
        }

        public Criteria andPicIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pic_id >=", value, "picId");
            return (Criteria) this;
        }

        public Criteria andPicIdLessThan(Integer value) {
            addCriterion("pic_id <", value, "picId");
            return (Criteria) this;
        }

        public Criteria andPicIdLessThanOrEqualTo(Integer value) {
            addCriterion("pic_id <=", value, "picId");
            return (Criteria) this;
        }

        public Criteria andPicIdIn(List<Integer> values) {
            addCriterion("pic_id in", values, "picId");
            return (Criteria) this;
        }

        public Criteria andPicIdNotIn(List<Integer> values) {
            addCriterion("pic_id not in", values, "picId");
            return (Criteria) this;
        }

        public Criteria andPicIdBetween(Integer value1, Integer value2) {
            addCriterion("pic_id between", value1, value2, "picId");
            return (Criteria) this;
        }

        public Criteria andPicIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pic_id not between", value1, value2, "picId");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIsNull() {
            addCriterion("pic_category is null");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIsNotNull() {
            addCriterion("pic_category is not null");
            return (Criteria) this;
        }

        public Criteria andPicCategoryEqualTo(String value) {
            addCriterion("pic_category =", value, "picCategory");
            return (Criteria) this;
        }

        public Criteria andPicCategoryNotEqualTo(String value) {
            addCriterion("pic_category <>", value, "picCategory");
            return (Criteria) this;
        }

        public Criteria andPicCategoryGreaterThan(String value) {
            addCriterion("pic_category >", value, "picCategory");
            return (Criteria) this;
        }

        public Criteria andPicCategoryGreaterThanOrEqualTo(String value) {
            addCriterion("pic_category >=", value, "picCategory");
            return (Criteria) this;
        }

        public Criteria andPicCategoryLessThan(String value) {
            addCriterion("pic_category <", value, "picCategory");
            return (Criteria) this;
        }

        public Criteria andPicCategoryLessThanOrEqualTo(String value) {
            addCriterion("pic_category <=", value, "picCategory");
            return (Criteria) this;
        }

        public Criteria andPicCategoryLike(String value) {
            addCriterion("pic_category like", value, "picCategory");
            return (Criteria) this;
        }

        public Criteria andPicCategoryNotLike(String value) {
            addCriterion("pic_category not like", value, "picCategory");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIn(List<String> values) {
            addCriterion("pic_category in", values, "picCategory");
            return (Criteria) this;
        }

        public Criteria andPicCategoryNotIn(List<String> values) {
            addCriterion("pic_category not in", values, "picCategory");
            return (Criteria) this;
        }

        public Criteria andPicCategoryBetween(String value1, String value2) {
            addCriterion("pic_category between", value1, value2, "picCategory");
            return (Criteria) this;
        }

        public Criteria andPicCategoryNotBetween(String value1, String value2) {
            addCriterion("pic_category not between", value1, value2, "picCategory");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIdIsNull() {
            addCriterion("pic_category_id is null");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIdIsNotNull() {
            addCriterion("pic_category_id is not null");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIdEqualTo(Integer value) {
            addCriterion("pic_category_id =", value, "picCategoryId");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIdNotEqualTo(Integer value) {
            addCriterion("pic_category_id <>", value, "picCategoryId");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIdGreaterThan(Integer value) {
            addCriterion("pic_category_id >", value, "picCategoryId");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("pic_category_id >=", value, "picCategoryId");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIdLessThan(Integer value) {
            addCriterion("pic_category_id <", value, "picCategoryId");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("pic_category_id <=", value, "picCategoryId");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIdIn(List<Integer> values) {
            addCriterion("pic_category_id in", values, "picCategoryId");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIdNotIn(List<Integer> values) {
            addCriterion("pic_category_id not in", values, "picCategoryId");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("pic_category_id between", value1, value2, "picCategoryId");
            return (Criteria) this;
        }

        public Criteria andPicCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("pic_category_id not between", value1, value2, "picCategoryId");
            return (Criteria) this;
        }

        public Criteria andPicLocationIsNull() {
            addCriterion("pic_location is null");
            return (Criteria) this;
        }

        public Criteria andPicLocationIsNotNull() {
            addCriterion("pic_location is not null");
            return (Criteria) this;
        }

        public Criteria andPicLocationEqualTo(String value) {
            addCriterion("pic_location =", value, "picLocation");
            return (Criteria) this;
        }

        public Criteria andPicLocationNotEqualTo(String value) {
            addCriterion("pic_location <>", value, "picLocation");
            return (Criteria) this;
        }

        public Criteria andPicLocationGreaterThan(String value) {
            addCriterion("pic_location >", value, "picLocation");
            return (Criteria) this;
        }

        public Criteria andPicLocationGreaterThanOrEqualTo(String value) {
            addCriterion("pic_location >=", value, "picLocation");
            return (Criteria) this;
        }

        public Criteria andPicLocationLessThan(String value) {
            addCriterion("pic_location <", value, "picLocation");
            return (Criteria) this;
        }

        public Criteria andPicLocationLessThanOrEqualTo(String value) {
            addCriterion("pic_location <=", value, "picLocation");
            return (Criteria) this;
        }

        public Criteria andPicLocationLike(String value) {
            addCriterion("pic_location like", value, "picLocation");
            return (Criteria) this;
        }

        public Criteria andPicLocationNotLike(String value) {
            addCriterion("pic_location not like", value, "picLocation");
            return (Criteria) this;
        }

        public Criteria andPicLocationIn(List<String> values) {
            addCriterion("pic_location in", values, "picLocation");
            return (Criteria) this;
        }

        public Criteria andPicLocationNotIn(List<String> values) {
            addCriterion("pic_location not in", values, "picLocation");
            return (Criteria) this;
        }

        public Criteria andPicLocationBetween(String value1, String value2) {
            addCriterion("pic_location between", value1, value2, "picLocation");
            return (Criteria) this;
        }

        public Criteria andPicLocationNotBetween(String value1, String value2) {
            addCriterion("pic_location not between", value1, value2, "picLocation");
            return (Criteria) this;
        }

        public Criteria andPicTitleIsNull() {
            addCriterion("pic_title is null");
            return (Criteria) this;
        }

        public Criteria andPicTitleIsNotNull() {
            addCriterion("pic_title is not null");
            return (Criteria) this;
        }

        public Criteria andPicTitleEqualTo(String value) {
            addCriterion("pic_title =", value, "picTitle");
            return (Criteria) this;
        }

        public Criteria andPicTitleNotEqualTo(String value) {
            addCriterion("pic_title <>", value, "picTitle");
            return (Criteria) this;
        }

        public Criteria andPicTitleGreaterThan(String value) {
            addCriterion("pic_title >", value, "picTitle");
            return (Criteria) this;
        }

        public Criteria andPicTitleGreaterThanOrEqualTo(String value) {
            addCriterion("pic_title >=", value, "picTitle");
            return (Criteria) this;
        }

        public Criteria andPicTitleLessThan(String value) {
            addCriterion("pic_title <", value, "picTitle");
            return (Criteria) this;
        }

        public Criteria andPicTitleLessThanOrEqualTo(String value) {
            addCriterion("pic_title <=", value, "picTitle");
            return (Criteria) this;
        }

        public Criteria andPicTitleLike(String value) {
            addCriterion("pic_title like", value, "picTitle");
            return (Criteria) this;
        }

        public Criteria andPicTitleNotLike(String value) {
            addCriterion("pic_title not like", value, "picTitle");
            return (Criteria) this;
        }

        public Criteria andPicTitleIn(List<String> values) {
            addCriterion("pic_title in", values, "picTitle");
            return (Criteria) this;
        }

        public Criteria andPicTitleNotIn(List<String> values) {
            addCriterion("pic_title not in", values, "picTitle");
            return (Criteria) this;
        }

        public Criteria andPicTitleBetween(String value1, String value2) {
            addCriterion("pic_title between", value1, value2, "picTitle");
            return (Criteria) this;
        }

        public Criteria andPicTitleNotBetween(String value1, String value2) {
            addCriterion("pic_title not between", value1, value2, "picTitle");
            return (Criteria) this;
        }

        public Criteria andPicMd5IsNull() {
            addCriterion("pic_md5 is null");
            return (Criteria) this;
        }

        public Criteria andPicMd5IsNotNull() {
            addCriterion("pic_md5 is not null");
            return (Criteria) this;
        }

        public Criteria andPicMd5EqualTo(String value) {
            addCriterion("pic_md5 =", value, "picMd5");
            return (Criteria) this;
        }

        public Criteria andPicMd5NotEqualTo(String value) {
            addCriterion("pic_md5 <>", value, "picMd5");
            return (Criteria) this;
        }

        public Criteria andPicMd5GreaterThan(String value) {
            addCriterion("pic_md5 >", value, "picMd5");
            return (Criteria) this;
        }

        public Criteria andPicMd5GreaterThanOrEqualTo(String value) {
            addCriterion("pic_md5 >=", value, "picMd5");
            return (Criteria) this;
        }

        public Criteria andPicMd5LessThan(String value) {
            addCriterion("pic_md5 <", value, "picMd5");
            return (Criteria) this;
        }

        public Criteria andPicMd5LessThanOrEqualTo(String value) {
            addCriterion("pic_md5 <=", value, "picMd5");
            return (Criteria) this;
        }

        public Criteria andPicMd5Like(String value) {
            addCriterion("pic_md5 like", value, "picMd5");
            return (Criteria) this;
        }

        public Criteria andPicMd5NotLike(String value) {
            addCriterion("pic_md5 not like", value, "picMd5");
            return (Criteria) this;
        }

        public Criteria andPicMd5In(List<String> values) {
            addCriterion("pic_md5 in", values, "picMd5");
            return (Criteria) this;
        }

        public Criteria andPicMd5NotIn(List<String> values) {
            addCriterion("pic_md5 not in", values, "picMd5");
            return (Criteria) this;
        }

        public Criteria andPicMd5Between(String value1, String value2) {
            addCriterion("pic_md5 between", value1, value2, "picMd5");
            return (Criteria) this;
        }

        public Criteria andPicMd5NotBetween(String value1, String value2) {
            addCriterion("pic_md5 not between", value1, value2, "picMd5");
            return (Criteria) this;
        }

        public Criteria andPicUrlIsNull() {
            addCriterion("pic_url is null");
            return (Criteria) this;
        }

        public Criteria andPicUrlIsNotNull() {
            addCriterion("pic_url is not null");
            return (Criteria) this;
        }

        public Criteria andPicUrlEqualTo(String value) {
            addCriterion("pic_url =", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotEqualTo(String value) {
            addCriterion("pic_url <>", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlGreaterThan(String value) {
            addCriterion("pic_url >", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlGreaterThanOrEqualTo(String value) {
            addCriterion("pic_url >=", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLessThan(String value) {
            addCriterion("pic_url <", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLessThanOrEqualTo(String value) {
            addCriterion("pic_url <=", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlLike(String value) {
            addCriterion("pic_url like", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotLike(String value) {
            addCriterion("pic_url not like", value, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlIn(List<String> values) {
            addCriterion("pic_url in", values, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotIn(List<String> values) {
            addCriterion("pic_url not in", values, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlBetween(String value1, String value2) {
            addCriterion("pic_url between", value1, value2, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicUrlNotBetween(String value1, String value2) {
            addCriterion("pic_url not between", value1, value2, "picUrl");
            return (Criteria) this;
        }

        public Criteria andPicNoteIsNull() {
            addCriterion("pic_note is null");
            return (Criteria) this;
        }

        public Criteria andPicNoteIsNotNull() {
            addCriterion("pic_note is not null");
            return (Criteria) this;
        }

        public Criteria andPicNoteEqualTo(String value) {
            addCriterion("pic_note =", value, "picNote");
            return (Criteria) this;
        }

        public Criteria andPicNoteNotEqualTo(String value) {
            addCriterion("pic_note <>", value, "picNote");
            return (Criteria) this;
        }

        public Criteria andPicNoteGreaterThan(String value) {
            addCriterion("pic_note >", value, "picNote");
            return (Criteria) this;
        }

        public Criteria andPicNoteGreaterThanOrEqualTo(String value) {
            addCriterion("pic_note >=", value, "picNote");
            return (Criteria) this;
        }

        public Criteria andPicNoteLessThan(String value) {
            addCriterion("pic_note <", value, "picNote");
            return (Criteria) this;
        }

        public Criteria andPicNoteLessThanOrEqualTo(String value) {
            addCriterion("pic_note <=", value, "picNote");
            return (Criteria) this;
        }

        public Criteria andPicNoteLike(String value) {
            addCriterion("pic_note like", value, "picNote");
            return (Criteria) this;
        }

        public Criteria andPicNoteNotLike(String value) {
            addCriterion("pic_note not like", value, "picNote");
            return (Criteria) this;
        }

        public Criteria andPicNoteIn(List<String> values) {
            addCriterion("pic_note in", values, "picNote");
            return (Criteria) this;
        }

        public Criteria andPicNoteNotIn(List<String> values) {
            addCriterion("pic_note not in", values, "picNote");
            return (Criteria) this;
        }

        public Criteria andPicNoteBetween(String value1, String value2) {
            addCriterion("pic_note between", value1, value2, "picNote");
            return (Criteria) this;
        }

        public Criteria andPicNoteNotBetween(String value1, String value2) {
            addCriterion("pic_note not between", value1, value2, "picNote");
            return (Criteria) this;
        }

        public Criteria andPicUpdateTimeIsNull() {
            addCriterion("pic_update_time is null");
            return (Criteria) this;
        }

        public Criteria andPicUpdateTimeIsNotNull() {
            addCriterion("pic_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andPicUpdateTimeEqualTo(Date value) {
            addCriterion("pic_update_time =", value, "picUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPicUpdateTimeNotEqualTo(Date value) {
            addCriterion("pic_update_time <>", value, "picUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPicUpdateTimeGreaterThan(Date value) {
            addCriterion("pic_update_time >", value, "picUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPicUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("pic_update_time >=", value, "picUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPicUpdateTimeLessThan(Date value) {
            addCriterion("pic_update_time <", value, "picUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPicUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("pic_update_time <=", value, "picUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPicUpdateTimeIn(List<Date> values) {
            addCriterion("pic_update_time in", values, "picUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPicUpdateTimeNotIn(List<Date> values) {
            addCriterion("pic_update_time not in", values, "picUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPicUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("pic_update_time between", value1, value2, "picUpdateTime");
            return (Criteria) this;
        }

        public Criteria andPicUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("pic_update_time not between", value1, value2, "picUpdateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pictures
     *
     * @mbggenerated do_not_delete_during_merge Fri Mar 23 15:34:22 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pictures
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}