package cn.edu.gdut.llc.mybatis.model;

import java.util.Date;

public class Pictures {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.pic_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer picId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.pic_category
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String picCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.pic_category_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer picCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.pic_location
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String picLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.pic_title
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String picTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.pic_md5
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String picMd5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.pic_url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String picUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.pic_note
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String picNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.pic_update_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Date picUpdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.pic_id
     *
     * @return the value of pictures.pic_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getPicId() {
        return picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.pic_id
     *
     * @param picId the value for pictures.pic_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setPicId(Integer picId) {
        this.picId = picId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.pic_category
     *
     * @return the value of pictures.pic_category
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getPicCategory() {
        return picCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.pic_category
     *
     * @param picCategory the value for pictures.pic_category
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setPicCategory(String picCategory) {
        this.picCategory = picCategory == null ? null : picCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.pic_category_id
     *
     * @return the value of pictures.pic_category_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getPicCategoryId() {
        return picCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.pic_category_id
     *
     * @param picCategoryId the value for pictures.pic_category_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setPicCategoryId(Integer picCategoryId) {
        this.picCategoryId = picCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.pic_location
     *
     * @return the value of pictures.pic_location
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getPicLocation() {
        return picLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.pic_location
     *
     * @param picLocation the value for pictures.pic_location
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setPicLocation(String picLocation) {
        this.picLocation = picLocation == null ? null : picLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.pic_title
     *
     * @return the value of pictures.pic_title
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getPicTitle() {
        return picTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.pic_title
     *
     * @param picTitle the value for pictures.pic_title
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setPicTitle(String picTitle) {
        this.picTitle = picTitle == null ? null : picTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.pic_md5
     *
     * @return the value of pictures.pic_md5
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getPicMd5() {
        return picMd5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.pic_md5
     *
     * @param picMd5 the value for pictures.pic_md5
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setPicMd5(String picMd5) {
        this.picMd5 = picMd5 == null ? null : picMd5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.pic_url
     *
     * @return the value of pictures.pic_url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getPicUrl() {
        return picUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.pic_url
     *
     * @param picUrl the value for pictures.pic_url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.pic_note
     *
     * @return the value of pictures.pic_note
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getPicNote() {
        return picNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.pic_note
     *
     * @param picNote the value for pictures.pic_note
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setPicNote(String picNote) {
        this.picNote = picNote == null ? null : picNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.pic_update_time
     *
     * @return the value of pictures.pic_update_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Date getPicUpdateTime() {
        return picUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.pic_update_time
     *
     * @param picUpdateTime the value for pictures.pic_update_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setPicUpdateTime(Date picUpdateTime) {
        this.picUpdateTime = picUpdateTime;
    }
}