package cn.edu.gdut.llc.mybatis.model;

import java.util.Date;

public class Policies {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policies.id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policies.title
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policies.cover_pic
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer coverPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policies.url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policies.keyword
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policies.note
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policies.origin
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policies.release_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policies.update_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policies.file
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policies.visit
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer visit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column policies.content
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policies.id
     *
     * @return the value of policies.id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policies.id
     *
     * @param id the value for policies.id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policies.title
     *
     * @return the value of policies.title
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policies.title
     *
     * @param title the value for policies.title
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policies.cover_pic
     *
     * @return the value of policies.cover_pic
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getCoverPic() {
        return coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policies.cover_pic
     *
     * @param coverPic the value for policies.cover_pic
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setCoverPic(Integer coverPic) {
        this.coverPic = coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policies.url
     *
     * @return the value of policies.url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policies.url
     *
     * @param url the value for policies.url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policies.keyword
     *
     * @return the value of policies.keyword
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policies.keyword
     *
     * @param keyword the value for policies.keyword
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policies.note
     *
     * @return the value of policies.note
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policies.note
     *
     * @param note the value for policies.note
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policies.origin
     *
     * @return the value of policies.origin
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policies.origin
     *
     * @param origin the value for policies.origin
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policies.release_time
     *
     * @return the value of policies.release_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policies.release_time
     *
     * @param releaseTime the value for policies.release_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policies.update_time
     *
     * @return the value of policies.update_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policies.update_time
     *
     * @param updateTime the value for policies.update_time
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policies.file
     *
     * @return the value of policies.file
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policies.file
     *
     * @param file the value for policies.file
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setFile(Integer file) {
        this.file = file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policies.visit
     *
     * @return the value of policies.visit
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getVisit() {
        return visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policies.visit
     *
     * @param visit the value for policies.visit
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setVisit(Integer visit) {
        this.visit = visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column policies.content
     *
     * @return the value of policies.content
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column policies.content
     *
     * @param content the value for policies.content
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}