package cn.edu.gdut.llc.mybatis.model;

public class ProjFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_file.proj_file_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer projFileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_file.projId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer projid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_file.fileId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer fileid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_file.proj_file_id
     *
     * @return the value of proj_file.proj_file_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getProjFileId() {
        return projFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_file.proj_file_id
     *
     * @param projFileId the value for proj_file.proj_file_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setProjFileId(Integer projFileId) {
        this.projFileId = projFileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_file.projId
     *
     * @return the value of proj_file.projId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getProjid() {
        return projid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_file.projId
     *
     * @param projid the value for proj_file.projId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setProjid(Integer projid) {
        this.projid = projid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_file.fileId
     *
     * @return the value of proj_file.fileId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_file.fileId
     *
     * @param fileid the value for proj_file.fileId
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setFileid(Integer fileid) {
        this.fileid = fileid;
    }
}