package cn.edu.gdut.llc.mybatis.model;

public class ProjPic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_pic.id
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_pic.projId
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Integer projid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column proj_pic.picId
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Integer picid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_pic.id
     *
     * @return the value of proj_pic.id
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_pic.id
     *
     * @param id the value for proj_pic.id
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_pic.projId
     *
     * @return the value of proj_pic.projId
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Integer getProjid() {
        return projid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_pic.projId
     *
     * @param projid the value for proj_pic.projId
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setProjid(Integer projid) {
        this.projid = projid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column proj_pic.picId
     *
     * @return the value of proj_pic.picId
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Integer getPicid() {
        return picid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column proj_pic.picId
     *
     * @param picid the value for proj_pic.picId
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setPicid(Integer picid) {
        this.picid = picid;
    }
}