package cn.edu.gdut.llc.mybatis.model;

import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.id
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.field
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.proj_name
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String projName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.proj_type
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String projType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.proj_head
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String projHead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.phone
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.enter_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Date enterTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.protocol
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String protocol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.company_name
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.register_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.register_money
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String registerMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.register_field
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String registerField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.oper_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Integer operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.status
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.logo
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Integer logo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.proj_url
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String projUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.visit
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Integer visit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.update_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.note
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.content
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.id
     *
     * @return the value of project.id
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.id
     *
     * @param id the value for project.id
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.field
     *
     * @return the value of project.field
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.field
     *
     * @param field the value for project.field
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.proj_name
     *
     * @return the value of project.proj_name
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getProjName() {
        return projName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.proj_name
     *
     * @param projName the value for project.proj_name
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setProjName(String projName) {
        this.projName = projName == null ? null : projName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.proj_type
     *
     * @return the value of project.proj_type
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getProjType() {
        return projType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.proj_type
     *
     * @param projType the value for project.proj_type
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setProjType(String projType) {
        this.projType = projType == null ? null : projType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.proj_head
     *
     * @return the value of project.proj_head
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getProjHead() {
        return projHead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.proj_head
     *
     * @param projHead the value for project.proj_head
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setProjHead(String projHead) {
        this.projHead = projHead == null ? null : projHead.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.phone
     *
     * @return the value of project.phone
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.phone
     *
     * @param phone the value for project.phone
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.enter_time
     *
     * @return the value of project.enter_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Date getEnterTime() {
        return enterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.enter_time
     *
     * @param enterTime the value for project.enter_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setEnterTime(Date enterTime) {
        this.enterTime = enterTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.protocol
     *
     * @return the value of project.protocol
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getProtocol() {
        return protocol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.protocol
     *
     * @param protocol the value for project.protocol
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setProtocol(String protocol) {
        this.protocol = protocol == null ? null : protocol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.company_name
     *
     * @return the value of project.company_name
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.company_name
     *
     * @param companyName the value for project.company_name
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.register_time
     *
     * @return the value of project.register_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.register_time
     *
     * @param registerTime the value for project.register_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.register_money
     *
     * @return the value of project.register_money
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getRegisterMoney() {
        return registerMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.register_money
     *
     * @param registerMoney the value for project.register_money
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setRegisterMoney(String registerMoney) {
        this.registerMoney = registerMoney == null ? null : registerMoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.register_field
     *
     * @return the value of project.register_field
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getRegisterField() {
        return registerField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.register_field
     *
     * @param registerField the value for project.register_field
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setRegisterField(String registerField) {
        this.registerField = registerField == null ? null : registerField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.oper_time
     *
     * @return the value of project.oper_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Integer getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.oper_time
     *
     * @param operTime the value for project.oper_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setOperTime(Integer operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.status
     *
     * @return the value of project.status
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.status
     *
     * @param status the value for project.status
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.logo
     *
     * @return the value of project.logo
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Integer getLogo() {
        return logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.logo
     *
     * @param logo the value for project.logo
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setLogo(Integer logo) {
        this.logo = logo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.proj_url
     *
     * @return the value of project.proj_url
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getProjUrl() {
        return projUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.proj_url
     *
     * @param projUrl the value for project.proj_url
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setProjUrl(String projUrl) {
        this.projUrl = projUrl == null ? null : projUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.visit
     *
     * @return the value of project.visit
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Integer getVisit() {
        return visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.visit
     *
     * @param visit the value for project.visit
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setVisit(Integer visit) {
        this.visit = visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.update_time
     *
     * @return the value of project.update_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.update_time
     *
     * @param updateTime the value for project.update_time
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.note
     *
     * @return the value of project.note
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.note
     *
     * @param note the value for project.note
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.content
     *
     * @return the value of project.content
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.content
     *
     * @param content the value for project.content
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}