package cn.edu.gdut.llc.mybatis.model;

import java.util.Date;

public class Type {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_title
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String typeTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String typeUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_parent_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Integer typeParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.is_parent
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Boolean isParent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.created
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Date created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.updated
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private Date updated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column type.type_icon
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    private String typeIcon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.id
     *
     * @return the value of type.id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.id
     *
     * @param id the value for type.id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_title
     *
     * @return the value of type.type_title
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getTypeTitle() {
        return typeTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_title
     *
     * @param typeTitle the value for type.type_title
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setTypeTitle(String typeTitle) {
        this.typeTitle = typeTitle == null ? null : typeTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_url
     *
     * @return the value of type.type_url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getTypeUrl() {
        return typeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_url
     *
     * @param typeUrl the value for type.type_url
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setTypeUrl(String typeUrl) {
        this.typeUrl = typeUrl == null ? null : typeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_parent_id
     *
     * @return the value of type.type_parent_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Integer getTypeParentId() {
        return typeParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_parent_id
     *
     * @param typeParentId the value for type.type_parent_id
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setTypeParentId(Integer typeParentId) {
        this.typeParentId = typeParentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.is_parent
     *
     * @return the value of type.is_parent
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Boolean getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.is_parent
     *
     * @param isParent the value for type.is_parent
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setIsParent(Boolean isParent) {
        this.isParent = isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.created
     *
     * @return the value of type.created
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.created
     *
     * @param created the value for type.created
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.updated
     *
     * @return the value of type.updated
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.updated
     *
     * @param updated the value for type.updated
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column type.type_icon
     *
     * @return the value of type.type_icon
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public String getTypeIcon() {
        return typeIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column type.type_icon
     *
     * @param typeIcon the value for type.type_icon
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    public void setTypeIcon(String typeIcon) {
        this.typeIcon = typeIcon == null ? null : typeIcon.trim();
    }
}