package cn.edu.gdut.llc.mybatis.model;

public class UserKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Wed Feb 07 18:09:49 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.depart_id
     *
     * @mbggenerated Wed Feb 07 18:09:49 CST 2018
     */
    private Integer departId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Wed Feb 07 18:09:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Wed Feb 07 18:09:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.depart_id
     *
     * @return the value of user.depart_id
     *
     * @mbggenerated Wed Feb 07 18:09:49 CST 2018
     */
    public Integer getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.depart_id
     *
     * @param departId the value for user.depart_id
     *
     * @mbggenerated Wed Feb 07 18:09:49 CST 2018
     */
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }
}