package cn.edu.gdut.llc.mybatis.mapper;

import cn.edu.gdut.llc.mybatis.model.Activities;
import cn.edu.gdut.llc.mybatis.model.ActivitiesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int countByExample(ActivitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int deleteByExample(ActivitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int insert(Activities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int insertSelective(Activities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    List<Activities> selectByExampleWithBLOBs(ActivitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    List<Activities> selectByExample(ActivitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    Activities selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") Activities record, @Param("example") ActivitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Activities record, @Param("example") ActivitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExample(@Param("record") Activities record, @Param("example") ActivitiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKeySelective(Activities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Activities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKey(Activities record);
}