package cn.edu.gdut.llc.mybatis.mapper;

import cn.edu.gdut.llc.mybatis.model.Alumnus;
import cn.edu.gdut.llc.mybatis.model.AlumnusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlumnusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int countByExample(AlumnusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int deleteByExample(AlumnusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int insert(Alumnus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int insertSelective(Alumnus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    List<Alumnus> selectByExampleWithBLOBs(AlumnusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    List<Alumnus> selectByExample(AlumnusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    Alumnus selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") Alumnus record, @Param("example") AlumnusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Alumnus record, @Param("example") AlumnusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByExample(@Param("record") Alumnus record, @Param("example") AlumnusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByPrimaryKeySelective(Alumnus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Alumnus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alumnus
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByPrimaryKey(Alumnus record);
}