package cn.edu.gdut.llc.mybatis.mapper;

import cn.edu.gdut.llc.mybatis.model.Funds;
import cn.edu.gdut.llc.mybatis.model.FundsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FundsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int countByExample(FundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int deleteByExample(FundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int insert(Funds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int insertSelective(Funds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    List<Funds> selectByExampleWithBLOBs(FundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    List<Funds> selectByExample(FundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    Funds selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") Funds record, @Param("example") FundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Funds record, @Param("example") FundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByExample(@Param("record") Funds record, @Param("example") FundsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByPrimaryKeySelective(Funds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Funds record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByPrimaryKey(Funds record);
}