package cn.edu.gdut.llc.mybatis.mapper;

import cn.edu.gdut.llc.mybatis.model.Guides;
import cn.edu.gdut.llc.mybatis.model.GuidesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GuidesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int countByExample(GuidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int deleteByExample(GuidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int insert(Guides record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int insertSelective(Guides record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    List<Guides> selectByExampleWithBLOBs(GuidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    List<Guides> selectByExample(GuidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    Guides selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") Guides record, @Param("example") GuidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Guides record, @Param("example") GuidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExample(@Param("record") Guides record, @Param("example") GuidesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKeySelective(Guides record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Guides record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table guides
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKey(Guides record);
}