package cn.edu.gdut.llc.mybatis.mapper;

import cn.edu.gdut.llc.mybatis.model.Infos;
import cn.edu.gdut.llc.mybatis.model.InfosExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InfosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int countByExample(InfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int deleteByExample(InfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int insert(Infos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int insertSelective(Infos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    List<Infos> selectByExampleWithBLOBs(InfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    List<Infos> selectByExample(InfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    Infos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") Infos record, @Param("example") InfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Infos record, @Param("example") InfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByExample(@Param("record") Infos record, @Param("example") InfosExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByPrimaryKeySelective(Infos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Infos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infos
     *
     * @mbggenerated Sat Apr 21 19:07:34 CST 2018
     */
    int updateByPrimaryKey(Infos record);
}