package cn.edu.gdut.llc.mybatis.mapper;

import cn.edu.gdut.llc.mybatis.model.Infopic;
import cn.edu.gdut.llc.mybatis.model.InfopicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InfopicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infopic
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    int countByExample(InfopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infopic
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    int deleteByExample(InfopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infopic
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infopic
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    int insert(Infopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infopic
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    int insertSelective(Infopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infopic
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    List<Infopic> selectByExample(InfopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infopic
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    Infopic selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infopic
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    int updateByExampleSelective(@Param("record") Infopic record, @Param("example") InfopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infopic
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    int updateByExample(@Param("record") Infopic record, @Param("example") InfopicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infopic
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    int updateByPrimaryKeySelective(Infopic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table infopic
     *
     * @mbggenerated Sat Jan 20 14:44:58 CST 2018
     */
    int updateByPrimaryKey(Infopic record);
}