package cn.edu.gdut.llc.mybatis.mapper;

import cn.edu.gdut.llc.mybatis.model.Knowledges;
import cn.edu.gdut.llc.mybatis.model.KnowledgesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KnowledgesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int countByExample(KnowledgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int deleteByExample(KnowledgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int insert(Knowledges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int insertSelective(Knowledges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    List<Knowledges> selectByExampleWithBLOBs(KnowledgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    List<Knowledges> selectByExample(KnowledgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    Knowledges selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") Knowledges record, @Param("example") KnowledgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Knowledges record, @Param("example") KnowledgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExample(@Param("record") Knowledges record, @Param("example") KnowledgesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKeySelective(Knowledges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Knowledges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table knowledges
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKey(Knowledges record);
}