package cn.edu.gdut.llc.mybatis.mapper;

import cn.edu.gdut.llc.mybatis.model.LoginRecord;
import cn.edu.gdut.llc.mybatis.model.LoginRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int countByExample(LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int deleteByExample(LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int insert(LoginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int insertSelective(LoginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    List<LoginRecord> selectByExample(LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    LoginRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") LoginRecord record, @Param("example") LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExample(@Param("record") LoginRecord record, @Param("example") LoginRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKeySelective(LoginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKey(LoginRecord record);
}