package cn.edu.gdut.llc.mybatis.mapper;

import cn.edu.gdut.llc.mybatis.model.Train;
import cn.edu.gdut.llc.mybatis.model.TrainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int countByExample(TrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int deleteByExample(TrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int insert(Train record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int insertSelective(Train record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    List<Train> selectByExampleWithBLOBs(TrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    List<Train> selectByExample(TrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    Train selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") Train record, @Param("example") TrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Train record, @Param("example") TrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByExample(@Param("record") Train record, @Param("example") TrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKeySelective(Train record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Train record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated Fri Mar 23 15:34:22 CST 2018
     */
    int updateByPrimaryKey(Train record);
}