package cn.edu.gdut.llc.mybatis.model.self;

import cn.edu.gdut.llc.mybatis.model.File;
import cn.edu.gdut.llc.mybatis.model.Pictures;
import cn.edu.gdut.llc.mybatis.model.Type;

import java.util.Date;
import java.util.List;

public class SelfInfos {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.id
     *
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.type
     *
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.title
     *
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.cover_pic
     *
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    private Integer coverPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.url
     *
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    private String infosUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.keyword
     *
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.note
     *
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.origin
     *
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.release_time
     *
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.update_time
     *
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.file
     *
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    private Integer file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.visit
     *
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    private Integer visit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column infos.content
     *
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.id
     *
     * @return the value of infos.id
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.id
     *
     * @param id the value for infos.id
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.type
     *
     * @return the value of infos.type
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.type
     *
     * @param type the value for infos.type
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.title
     *
     * @return the value of infos.title
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.title
     *
     * @param title the value for infos.title
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.cover_pic
     *
     * @return the value of infos.cover_pic
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public Integer getCoverPic() {
        return coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.cover_pic
     *
     * @param coverPic the value for infos.cover_pic
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public void setCoverPic(Integer coverPic) {
        this.coverPic = coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.url
     *
     * @return the value of infos.url
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public String getInfosUrl() {
        return infosUrl;
    }

    public void setInfosUrl(String infosUrl) {
        this.infosUrl = infosUrl;
    }
    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.url
     *
     * @param url the value for infos.url
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.keyword
     *
     * @return the value of infos.keyword
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.keyword
     *
     * @param keyword the value for infos.keyword
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.note
     *
     * @return the value of infos.note
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.note
     *
     * @param note the value for infos.note
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.origin
     *
     * @return the value of infos.origin
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.origin
     *
     * @param origin the value for infos.origin
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.release_time
     *
     * @return the value of infos.release_time
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.release_time
     *
     * @param releaseTime the value for infos.release_time
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.update_time
     *
     * @return the value of infos.update_time
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.update_time
     *
     * @param updateTime the value for infos.update_time
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.file
     *
     * @return the value of infos.file
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public Integer getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.file
     *
     * @param file the value for infos.file
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public void setFile(Integer file) {
        this.file = file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.visit
     *
     * @return the value of infos.visit
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public Integer getVisit() {
        return visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.visit
     *
     * @param visit the value for infos.visit
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public void setVisit(Integer visit) {
        this.visit = visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column infos.content
     *
     * @return the value of infos.content
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column infos.content
     *
     * @param content the value for infos.content
     * @mbggenerated Mon Dec 11 21:09:48 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    private String picUrl;
    private String typeTitle;
    private String fileUrl;

    public List<Type> getTypeList() {
        return typeList;
    }

    public String getFileUrl() {
        return fileUrl;
    }

    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl;
    }

    public List<File> getFileList() {
        return fileList;
    }

    public void setFileList(List<File> fileList) {
        this.fileList = fileList;
    }

    public void setTypeList(List<Type> typeList) {
        this.typeList = typeList;
    }

    public List<Pictures> getPicList() {
        return picList;
    }

    public void setPicList(List<Pictures> picList) {
        this.picList = picList;
    }

    private List<Type> typeList;
    private List<Pictures> picList;
    private List<File> fileList;

    public String getPicUrl() {
        return picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl == null ? null : picUrl.trim();
    }

    public String getTypeTitle() {
        return typeTitle;
    }

    public void setTypeTitle(String typeTitle) {
        this.typeTitle = typeTitle == null?null : typeTitle.trim();
    }

    private Integer preId;
    private Integer nextId;
    private String preTitle;
    private String nextTitle;

    public Integer getPreId() {
        return preId;
    }

    public void setPreId(Integer preId) {
        this.preId = preId;
    }

    public Integer getNextId() {
        return nextId;
    }

    public void setNextId(Integer nextId) {
        this.nextId = nextId;
    }

    public String getPreTitle() {
        return preTitle;
    }

    public void setPreTitle(String preTitle) {
        this.preTitle = preTitle == null ? null : preTitle.trim();
    }

    public String getNextTitle() {
        return nextTitle;
    }

    public void setNextTitle(String nextTitle) {
        this.nextTitle = nextTitle == null ? null : nextTitle.trim();
    }

}