package cn.edu.gdut.llc.mybatis.model.self;

import java.util.Date;

public class SelfAlumnus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumnus.id
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumnus.title
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumnus.cover_pic
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    private Integer coverPic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumnus.url
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumnus.keyword
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumnus.note
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumnus.origin
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumnus.release_time
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    private Date releaseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumnus.update_time
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumnus.file
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    private Integer file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumnus.visit
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    private Integer visit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alumnus.content
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumnus.id
     *
     * @return the value of alumnus.id
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumnus.id
     *
     * @param id the value for alumnus.id
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumnus.title
     *
     * @return the value of alumnus.title
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumnus.title
     *
     * @param title the value for alumnus.title
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumnus.cover_pic
     *
     * @return the value of alumnus.cover_pic
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public Integer getCoverPic() {
        return coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumnus.cover_pic
     *
     * @param coverPic the value for alumnus.cover_pic
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public void setCoverPic(Integer coverPic) {
        this.coverPic = coverPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumnus.url
     *
     * @return the value of alumnus.url
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumnus.url
     *
     * @param url the value for alumnus.url
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumnus.keyword
     *
     * @return the value of alumnus.keyword
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumnus.keyword
     *
     * @param keyword the value for alumnus.keyword
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword == null ? null : keyword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumnus.note
     *
     * @return the value of alumnus.note
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumnus.note
     *
     * @param note the value for alumnus.note
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumnus.origin
     *
     * @return the value of alumnus.origin
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumnus.origin
     *
     * @param origin the value for alumnus.origin
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumnus.release_time
     *
     * @return the value of alumnus.release_time
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public Date getReleaseTime() {
        return releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumnus.release_time
     *
     * @param releaseTime the value for alumnus.release_time
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public void setReleaseTime(Date releaseTime) {
        this.releaseTime = releaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumnus.update_time
     *
     * @return the value of alumnus.update_time
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumnus.update_time
     *
     * @param updateTime the value for alumnus.update_time
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumnus.file
     *
     * @return the value of alumnus.file
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public Integer getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumnus.file
     *
     * @param file the value for alumnus.file
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public void setFile(Integer file) {
        this.file = file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumnus.visit
     *
     * @return the value of alumnus.visit
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public Integer getVisit() {
        return visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumnus.visit
     *
     * @param visit the value for alumnus.visit
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public void setVisit(Integer visit) {
        this.visit = visit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alumnus.content
     *
     * @return the value of alumnus.content
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alumnus.content
     *
     * @param content the value for alumnus.content
     *
     * @mbggenerated Sun Dec 10 14:23:12 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }


    private String picUrl;

    public String getPicUrl(){return  picUrl;}
    public void setPicUrl(String picUrl){this.picUrl = picUrl == null ? null : picUrl.trim(); }

}