package cn.edu.gdut.llc.mybatis.model.self;

import java.util.Date;

public class SelfPictures {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.id
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.category
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.category_id
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    private Integer categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.location
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.title
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.md5
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.url
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.note
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pictures.update_time
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.id
     *
     * @return the value of pictures.id
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.id
     *
     * @param id the value for pictures.id
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.category
     *
     * @return the value of pictures.category
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.category
     *
     * @param category the value for pictures.category
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.category_id
     *
     * @return the value of pictures.category_id
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.category_id
     *
     * @param categoryId the value for pictures.category_id
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.location
     *
     * @return the value of pictures.location
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.location
     *
     * @param location the value for pictures.location
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.title
     *
     * @return the value of pictures.title
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.title
     *
     * @param title the value for pictures.title
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.md5
     *
     * @return the value of pictures.md5
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.md5
     *
     * @param md5 the value for pictures.md5
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.url
     *
     * @return the value of pictures.url
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.url
     *
     * @param url the value for pictures.url
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.note
     *
     * @return the value of pictures.note
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.note
     *
     * @param note the value for pictures.note
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pictures.update_time
     *
     * @return the value of pictures.update_time
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pictures.update_time
     *
     * @param updateTime the value for pictures.update_time
     *
     * @mbggenerated Tue Jan 09 17:14:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    private String infoTitle;
    private String typeTitle;

    public String getTypeTitle() {
        return typeTitle;
    }

    public void setTypeTitle(String typeTitle) {
        this.typeTitle = typeTitle == null?null : typeTitle.trim();
    }

    public String getInfoTitle() {
        return infoTitle;
    }

    public void setInfoTitle(String infoTitle) {
        this.infoTitle = infoTitle == null ? null : infoTitle.trim();
    }
}